### PR TITLE
WIP Initial build-openj9 github action commit

### PR DESCRIPTION
**Pull request by sophia-guo**
Support jdk8 on [ubuntu-16.04, ubuntu-18.04]
jdk11, ..., jdk14 on [ubuntu-16.04, ubuntu-18.04, macos-10.15]
jdk11 on [windows-2016]

### CODE REVIEW

**Comment by pshipton** [comment]
Set as WIP since I think we need an Eclipse CQ for this. @smlambert are you going to handle this?

@sophia-guo the commit title should be more descriptive of the change. Can you please also add new lines at the end, for the files which don't have them. Should be obvious which ones from the "File changes" view.

**Comment by smlambert** [comment]
Not sure I know what needs to be done to create a CQ, if you can give me some guidance @pshipton, I can take care of it.

**Comment by pshipton** [comment]
@smlambert 
https://www.eclipse.org/projects/handbook/#pmi-commands-cq
https://projects.eclipse.org/projects/technology.openj9
https://projects.eclipse.org/projects/technology.openj9/cq/create

**Comment by sophia-guo** [comment]
Nightly builds are based on master of https://github.com/eclipse/openj9. Wondered should we move the PR https://github.com/eclipse/openj9/pull/9576 to this repo? @pshipton

**Comment by pshipton** [comment]
> Wondered should we move the PR eclipse/openj9#9576 to this repo?

What are the side effects/restrictions of doing that? Since we are testing on a schedule I don't see that it matters, using this repo is fine. If we want to trigger off some event, we might need something in OpenJ9. I think moving it here to start makes sense, and we can add something to OpenJ9 later if necessary.

**Comment by smlambert** [comment]
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22245

**Comment by smlambert** [comment]
We have some additional work to do in response to today's note on CQ:

> We have completed an initial review of the code and have a few comments:
> 
> - As this is an initial project code contribution, we should only be seeing the
> project licenses in the headers (EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH
>  * Classpath-exception-2.0 OR GPL-2.0 WITH OpenJDK-assembly-exception-1.0). Our
> scan picked up only 4 files with license information, three of which were MIT
> licensed and the other EPL-2.0 only. The other 16 files in the package have no
> license information attached. You have indicated the reason for the presence of
> the MIT code above, but again this is an initial contribution and we should not
> be seeing licenses outside of those approved for the project.
> 
> - Please update the attachment to ensure that all files include the proper
> Eclipse header information, as illustrated here:
> 
> https://www.eclipse.org/projects/tools/documentation.php?id=technology.openj9
> 
> As well, please ensure that you are making use of the eclipse.org namespace.
> 
> Once the above issued have been addressed, we can proceed to check in the code
> for review.
>

**Comment by sophia-guo** [comment]
@pshipton Does this https://github.com/eclipse/build-openj9/pull/1#issuecomment-648955154 mean adding the standard copyright and license (same as openj9 one) to all files? And remove the MIT License file for initial commit and add back later in a separate PR?

**Comment by pshipton** [comment]
You can't change a license, from MIT to Eclipse/Apache or otherwise, unless you wrote/own the code outright and are choosing the license to make it available. 

There is documentation here https://www.eclipse.org/projects/handbook/#ip-initial-contribution

Sounds like we need to make an initial contribution to the repo with only Eclipse licensed files before trying to add the MIT licensed files. @smlambert according to the doc you'll need another CQ for the MIT licensed files.

**Comment by sophia-guo** [comment]
Added Eclipse License to all workflows yaml files, two typescript files, action.yml and README.md. Others are github action related property files, which are under MIT licenses I believe and is defined under package.json as :

```
"license": "MIT",
```
Just temporarily removed the file  package.json 

Attached zip file @smlambert 
[build-openj9-1.zip](https://github.com/eclipse/build-openj9/files/4854103/build-openj9-1.zip)

**Comment by smlambert** [comment]
Updated [CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22245) with new attachment and a comment about the plan to bring in the few MIT licensed files via a separate CQ, once we have initial contribution CQ complete.

**Comment by smlambert** [comment]
CQ progress:

"We have completed preliminary triage and you may now proceed to check the
attached content into the project’s repository.  A comprehensive IP review has
been added to the IP Team’s work queue and will be scheduled at a later date.

Please ensure you include necessary legal documentation files such as Notice,
License, Contributing, etc. when you move the content code to the repo.  Our
Legal Documentation Tooling can help with that:

https://www.eclipse.org/projects/tools/documentation.php?id=technology.openj9"

@sophia-guo - we can proceed with this PR, can you make sure to add the NOTICE,
LICENCE, CONTRIBUTING files (the link above creates an initial version of those files for you).

**Review by smlambert — COMMENTED** [review]
Given the [initial CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22245) is approved, this can be merged once a License file, Notice file and Contributing file are added.

@sophia-guo - can you log in to https://www.eclipse.org/projects/tools/documentation.php?id=technology.openj9 and generate those files?  If not, let me know I will send you files to add to this PR so we can merge it.

**Review by smlambert — APPROVED** [review]
thanks @sophia-guo !

**Pull request merged**
